version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    working_dir: /app/
    ports:
      - 3000:3000
      - 8000:8000
      - 8080:8080
    stdin_open: true
    tty: true
    networks:
      - surf-king-network

  postgres:
    image: postgres:12.6
    environment:
      POSTGRES_USER: "surfking"
      POSTGRES_PASSWORD: "Nazare@21#test"
      POSTGRES_DB: "surfking"
    ports:
      - 15432:5432
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - surf-king-network
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "joselitofilhoo@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "Nazare@21#test"
    ports:
      - 16543:80
    depends_on:
      - postgres
    networks:
      - surf-king-network

volumes:
  data:

networks: 
  surf-king-network:
    driver: bridge